import { chromium } from 'playwright';
import assert from 'node:assert/strict';
await import('./make-atlas.js');
const browser = await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE || '/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page = await browser.newPage({ viewport:{width:1440,height:1150},acceptDownloads:true });
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.argv[2] || 'http://127.0.0.1:8317/');
await page.locator('#example').click();
await page.waitForTimeout(600);
await page.screenshot({path:'/tmp/lacuna-desktop.png',fullPage:true});
const memory=await page.locator('#canvas').evaluate(c=>c.toDataURL());
await page.locator('#compare').click();
await page.waitForTimeout(200);
const plain=await page.locator('#canvas').evaluate(c=>c.toDataURL());
assert.notEqual(memory,plain);
await page.screenshot({path:'/tmp/lacuna-plain.png',fullPage:true});
await page.locator('#compare').click();
await page.locator('#ghosts').click();
await page.waitForTimeout(200);
await page.screenshot({path:'/tmp/lacuna-currents.png',fullPage:true});
await page.locator('#new').click();
assert.equal(await page.locator('#counts').textContent(),'0 marks · 0 memories');
async function draw(points){await page.locator('#canvas').scrollIntoViewIfNeeded();const box=await page.locator('#canvas').boundingBox();const xy=(x,y)=>({x:box.x+x/1000*box.width,y:box.y+y/700*box.height});const a=xy(...points[0]);await page.mouse.move(a.x,a.y);await page.mouse.down();for(const p of points.slice(1)){const q=xy(...p);await page.mouse.move(q.x,q.y,{steps:2});}await page.mouse.up();}
await draw(Array.from({length:60},(_,i)=>{const a=i/59*Math.PI*2;return [500+140*Math.cos(a),350+140*Math.sin(a)];}));
assert.equal(await page.locator('#counts').textContent(),'1 mark · 0 memories');
await page.locator('#release').click();
assert.equal(await page.locator('#counts').textContent(),'0 marks · 1 memory');
await draw([[280,310],[350,310],[450,310],[550,310],[650,310]]);
assert.equal(await page.locator('#counts').textContent(),'1 mark · 1 memory');
await page.waitForTimeout(600);
await page.reload();
assert.equal(await page.locator('#counts').textContent(),'1 mark · 1 memory');
await page.locator('#erase').click();
await draw([[460,280],[460,340]]);
assert.equal(await page.locator('#counts').textContent(),'0 marks · 2 memories');
await page.locator('#undo').click();
assert.equal(await page.locator('#counts').textContent(),'1 mark · 1 memory');
await page.waitForTimeout(500);
const uncut=await page.evaluate(()=>JSON.parse(localStorage.getItem('lacuna.study.v1')));
await page.locator('#lift').click();
await draw([[510,260],[510,360]]);
assert.equal(await page.locator('#counts').textContent(),'1 mark · 2 memories');
await page.waitForTimeout(500);
const lifted=await page.evaluate(()=>JSON.parse(localStorage.getItem('lacuna.study.v1')));
assert.ok(lifted.ghosts.at(-1).paths.length>0);
assert.notDeepEqual(lifted.strokes,uncut.strokes);
const {validateDocument,makeField}=await import('../field.js');
validateDocument(lifted);
assert.ok(Math.hypot(...Object.values(makeField([lifted.ghosts.at(-1)])(510,310)))>0);
await page.locator('#canvas').scrollIntoViewIfNeeded();
await page.screenshot({path:'/tmp/lacuna-lifted.png',fullPage:true});
await page.reload();
assert.equal(await page.locator('#counts').textContent(),'1 mark · 2 memories');
await page.locator('#reverse').click();
await page.waitForTimeout(500);
const reversedLift=await page.evaluate(()=>JSON.parse(localStorage.getItem('lacuna.study.v1')));
assert.deepEqual(reversedLift.ghosts.at(-1).paths[0],[...lifted.ghosts.at(-1).paths[0]].reverse());
await page.locator('#undo').click();
// Reopen the pre-cut fixture for the existing export/import checks.
await page.locator('#file').setInputFiles({name:'uncut.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(uncut))});
await page.waitForTimeout(200);
const dl=page.waitForEvent('download');await page.locator('#export').click();await (await dl).saveAs('/tmp/lacuna-export.png');
const jsonDownload=page.waitForEvent('download');await page.locator('#save-study').click();await(await jsonDownload).saveAs('/tmp/lacuna-study.json');
await page.locator('#new').click();
await page.locator('#file').setInputFiles('/tmp/lacuna-study.json');
await page.waitForTimeout(300);
assert.equal(await page.locator('#counts').textContent(),'1 mark · 1 memory');
await page.locator('#file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});
await page.waitForTimeout(100);
assert.equal(await page.locator('#counts').textContent(),'1 mark · 1 memory');
await page.locator('#about').click();assert.equal(await page.locator('dialog').evaluate(d=>d.open),true);await page.keyboard.press('Escape');
await page.locator('#example').click();
await page.locator('[data-score=orbit]').click();
await page.waitForTimeout(400);
assert.equal(await page.locator('#counts').textContent(),'18 marks · 2 memories');
const oldInk=await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('lacuna.study.v1')).strokes));
await page.locator('#reverse').click();
await page.waitForTimeout(500);
assert.equal(await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('lacuna.study.v1')).strokes)),oldInk);
await page.locator('#forget').click();
assert.equal(await page.locator('#counts').textContent(),'18 marks · 1 memory');
await page.locator('#undo').click();
assert.equal(await page.locator('#counts').textContent(),'18 marks · 2 memories');
await page.locator('[data-score=fault]').click();
assert.equal(await page.locator('#counts').textContent(),'12 marks · 1 memory');
const pairDownload=page.waitForEvent('download');await page.locator('#print-pair').click();await(await pairDownload).saveAs('/tmp/lacuna-pair.html');
const print=await browser.newPage();let network=0;print.on('request',r=>{if(r.url().startsWith('http'))network++;});await print.goto('file:///tmp/lacuna-pair.html');
assert.equal(await print.locator('svg').count(),2);await print.locator('#show').check();assert.equal(await print.locator('.currents').first().evaluate(g=>getComputedStyle(g).display),'block');assert.equal(network,0);await print.screenshot({path:'/tmp/lacuna-pair.png',fullPage:true});await print.close();
const processPage=await browser.newPage({viewport:{width:1440,height:850}});
await processPage.goto(new URL('../.local/atlas/opening-process.html',import.meta.url).href);
assert.equal(await processPage.locator('svg').count(),3);
await processPage.screenshot({path:'/tmp/lacuna-process.png',fullPage:true});
await processPage.close();
await page.locator('[data-score=opening]').click();
assert.equal(await page.locator('#counts').textContent(),'16 marks · 1 memory');
await page.waitForTimeout(700);
const opening=await page.evaluate(()=>JSON.parse(localStorage.getItem('lacuna.study.v1')));
validateDocument(opening);
assert.ok(opening.ghosts[0].paths.length>10);
assert.ok(opening.strokes.some(s=>s.lifted));
await page.locator('#canvas').scrollIntoViewIfNeeded();
await page.screenshot({path:'/tmp/lacuna-opening.png',fullPage:true});
await page.locator('#example').click();
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(200);
await page.screenshot({path:'/tmp/lacuna-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);
console.log('Passed desktop drawing, erasure, memory comparison, undo, persistence, PNG/JSON export, import validation, dialog, and mobile layout.');
const touch=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const mobile=await touch.newPage();
mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto('http://127.0.0.1:8317/');
await mobile.locator('#about').tap();
await mobile.waitForTimeout(400);
assert.equal(await mobile.locator('dialog').evaluate(d=>d.open),true);
await mobile.locator('dialog').evaluate(d=>d.close());
await mobile.locator('#canvas').scrollIntoViewIfNeeded();
const touchBox=await mobile.locator('#canvas').boundingBox(), session=await mobile.context().newCDPSession(mobile);
const touchPoint=(x,y)=>({x:touchBox.x+x/1000*touchBox.width,y:touchBox.y+y/700*touchBox.height});
await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touchPoint(300,300)]});
for(let x=310;x<700;x+=20)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touchPoint(x,300)]});
await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
assert.equal(await mobile.locator('#counts').textContent(),'1 mark · 0 memories');
// CDP replays the whole drawing gesture in milliseconds. Let that gesture
// settle before sending a separate tap, rather than a double-tap sequence.
await mobile.waitForTimeout(400);
await mobile.locator('#release').tap();
await mobile.waitForFunction(()=>document.getElementById('counts').textContent==='0 marks · 1 memory',{},{timeout:3000});
assert.equal(await mobile.locator('#counts').textContent(),'0 marks · 1 memory');
await touch.close();
assert.deepEqual(errors,[]);
console.log('Passed editable specimens, reversal without retroactive changes, forgetting/undo, offline paired print, and real touch input.');
await browser.close();
